### ISSUE TITLE
[solved] SyntaxError: Unexpected token import after running the script

### ISSUE THREAD

**Issue by teriteriteri** [GertjanReynaert/react-intl-translations-manager#119]
I encountered with a syntaxError when running manage:translations.
I have run the npm script "$ npm i --save-dev react-intl-translations-manager" already.

Is there any additional npm intall needed? Thanks!

here's the error:

....\translationRunner.js:1
(function (exports, require, module, __filename, __dirname) { import manageTranslations from 'react-intl-translations-manager';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pokedex@1.1.17 manage-trans: `node ./src/translationRunner.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pokedex@1.1.17 manage-trans script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by teriteriteri** [comment]
update:   
Problem is,
I comment out "const manageTranslations = require('react-intl-translations-manager').default;"
and used es2015 import instead.
// import manageTranslations from 'react-intl-translations-manager';

That caused the error since node does not support es6.
Problem solved by using the default way to import manageTranslations.
